In [18]:
import random
import pandas as pd
import numpy as np
import math
#create our matrix starting state, 0 will denote the open space
options = [0,1,2,3,4,5,6,7,8]
#randomize the starting state
random.shuffle(options)
print(options)
StartingMatrix = np.zeros((3,3))
#create matrix's
for i in range (0, 3):
    print(i)
    for j in range (0, 3):
        print(j)
        StartingMatrix[i][j] = options[(i*3)+j]
print(StartingMatrix)
endMatrix = np.zeros((3,3))
endstate = [1,2,3,8,0,4,7,6,5]
for i in range (0, 3):
    print(i)
    for j in range (0, 3):
        print(j)
        endMatrix[i][j] = endstate[(i*3)+j]
print(endMatrix)

[5, 3, 2, 4, 6, 1, 7, 8, 0]
0
0
1
2
1
0
1
2
2
0
1
2
[[5. 3. 2.]
 [4. 6. 1.]
 [7. 8. 0.]]
0
0
1
2
1
0
1
2
2
0
1
2
[[1. 2. 3.]
 [8. 0. 4.]
 [7. 6. 5.]]


In [25]:
#we will define cost as the number of pieces out of place
class uniformcostsearch:
    def __init__(self, endstate, endMatrix, startingMaxtrix, startingStatelist):
        self.endstate = endstate
        self.endMatrix = endMatrix
        self.startingMaxtrix = startingMaxtrix
        self.startingStatelist = startingStatelist
        #calculate the cost of each move for uniform cost search cost is the number of miss placed peices
    def costOfCandidateState(self, startingMaxtrix, endMatrix):
        cost = 0
        for i in range (0, 3): 
            for j in range (0, 3):
                if(startingMaxtrix[i][j] != endMatrix[i][j] and startingMaxtrix[i][j] != 0):
                    cost += 1            
        return(cost)
        #this will find possible now moves and call costofCandidateState to determine that moves cost
        #this information will be used to create a new node
        #parameters are matrix state of current node, depth at current node and the node itself
        #this will return a list of potentail new nodes 
    def findPossibleMoves(self, currentMatrixState, depth ,node):
        possibleMoves = []
        tempMatrix = np.zeros((3,3))
        #depth is increased based off the node feeding into its depth
        depth += 1
        #creating a temp matrix to do the calcaulations with
        for i in range (0, 3):
            for j in range (0, 3):
                tempMatrix[i][j] = currentMatrixState[i][j]
        zerolocx = 0
        zerolocy = 0
        cost = -1
        #find where 0 which denotes the black space is located
        for i in range (0, 3):
            for j in range (0, 3):
                if(currentMatrixState[i][j] == 0):
                    zerolocx = i
                    zerolocy = j
        
        #these four if statements check is a state can be reach and if it can will create a new node with
        #a cost associated with it matrix state
        if(zerolocx > 0):
            tempMatrix[zerolocx][zerolocy] = currentMatrixState[zerolocx-1][zerolocy]
            tempMatrix[zerolocx-1][zerolocy] = 0
            cost = self.costOfCandidateState(tempMatrix.copy(), self.endMatrix)
            
            node4 = Node(tempMatrix.copy(), depth, cost)
            possibleMoves.append(node4)
            #possibleMoves.append(Node(tempMatrix.copy(), depth, cost))
            for i in range (0, 3):
                for j in range (0, 3):
                    tempMatrix[i][j] = currentMatrixState[i][j]
        if(zerolocx < 2):
            tempMatrix[zerolocx][zerolocy] = currentMatrixState[zerolocx+1][zerolocy]
            tempMatrix[zerolocx+1][zerolocy] = 0
            cost = self.costOfCandidateState(tempMatrix.copy(), self.endMatrix)
            node1 = Node(tempMatrix.copy(), depth, cost)
            possibleMoves.append(node1)
            for i in range (0, 3):
                for j in range (0, 3):
                    tempMatrix[i][j] = currentMatrixState[i][j]
        if(zerolocy > 0):
            tempMatrix[zerolocx][zerolocy] = currentMatrixState[zerolocx][zerolocy-1]
            tempMatrix[zerolocx][zerolocy-1] = 0
            cost = self.costOfCandidateState(tempMatrix.copy(), self.endMatrix)
            node2 = Node(tempMatrix.copy(), depth, cost)
            possibleMoves.append(node2)
            
            for i in range (0, 3):
                for j in range (0, 3):
                    tempMatrix[i][j] = currentMatrixState[i][j]
        if(zerolocy < 2):
            tempMatrix[zerolocx][zerolocy] = currentMatrixState[zerolocx][zerolocy+1]
            tempMatrix[zerolocx][zerolocy+1] = 0
            cost = self.costOfCandidateState(tempMatrix.copy(), self.endMatrix)
            node3 = Node(tempMatrix.copy(), depth, cost)
            possibleMoves.append(node3)
            #possibleMoves.append(Node(tempMatrix.copy(), depth, cost))
            for i in range (0, 3):
                for j in range (0, 3):
                    tempMatrix[i][j] = currentMatrixState[i][j]
        #assign the node used to create each new node as its past node
        for i in range (0, len(possibleMoves)):                      
            possibleMoves[i].pastnode = node
        return(possibleMoves)
    #generates the tree it will return the node which first solves the puzzle which can be used to retrieve a move path
    def generatetree(self):
        candidateNodeList = []
        candidateNodeList1 = []
        #create our starting node 
        node = Node(current = self.startingMaxtrix, depth = 0, cost = -1)
        #a list which hold all possible moves
        candidateNodeList.append(node)
        candidateNodeList[0].cost = self.costOfCandidateState(candidateNodeList[0].currentMatrix, self.endMatrix)
        #a list which keeps track of which matrix states have already be visited
        matchList = []
        for i in range (0, 10000):
            #find lowest cost node
            mincost = 1000000000
            indexOfNextChoice = 0
            print('iteration')
            #first find the lowest cost move in the candidateNodeList
            for j in range (0, len(candidateNodeList)):
                
                if(candidateNodeList[j].cost < mincost and candidateNodeList[j].cost != -1):
                    indexOfNextChoice = j
                    mincost = candidateNodeList[j].cost
                    #This will end generate tree when a cost of 0 has been found denoting the final state
                    if(mincost == 0):
                        print('here')
                        print(candidateNodeList[j].currentMatrix)
                        print("total matrix's visited to reach goal state")
                        print(i)
                        return(candidateNodeList[j])
                        
            
            print('chosen node')
            print(candidateNodeList[indexOfNextChoice].currentMatrix)
            print(candidateNodeList[indexOfNextChoice].cost)
            #matchlist will add the node chosen this time so it will not be visited again
            matchList.append(candidateNodeList[indexOfNextChoice].currentMatrix)
            
            #generate new possible moves based off of the new selected node to be used in the next loop
            candidateNodeList1 = (self.findPossibleMoves(candidateNodeList[indexOfNextChoice].currentMatrix,candidateNodeList[indexOfNextChoice].depth, candidateNodeList[indexOfNextChoice]))
            #add all new nodes the candidateNodeList         
            candidateNodeList = np.concatenate((candidateNodeList, candidateNodeList1), axis=0)
            #delete the node which was just visited as it is no longer a candidate
            candidateNodeList = np.delete(candidateNodeList, indexOfNextChoice, 0)
            m = 0
            #search through the candidateNodeList to insure that no nodes which have already be visited are in the list
            #this can occure as the same matrix state can be reach though more than one combination of moves
            while m < len(candidateNodeList):
                m2 = candidateNodeList[m].currentMatrix
                #print('m2')
                #print(m2)
                for k in range(0, len(matchList)):
                    
                    cost1 = 0
                    m1 = matchList[k]
                    #print('m1')
                    #print(m1)
                    
                    
                    for b in range (0, 3):
                        for v in range (0, 3):                         
                            if(m1[b][v] != m2[b][v]):
                                cost1 += 1                              
                    if(cost1 == 0 and m != len(candidateNodeList)):
                        #print('check of if last node exist')
                        #print(m)
                        #print(len(candidateNodeList))
                        #print(candidateNodeList[m].currentMatrix)
                        #print(m1)
                        candidateNodeList = np.delete(candidateNodeList, m)                     
                        k = len(matchList)
                m += 1
            
            
    

In [26]:
#the node class which contain the matrix stored at each node its depth cost and the node which created it
#this is used to produce a path the secondary depth huristic used in the A* algorithm
class Node:
    def __init__(self, current, depth, cost):
        self.currentMatrix = current
        self.depth = depth
        self.cost = cost
        self.pastnode = None
    def getdepth():
        return(depth)
    def getCurrentState():
        return(self.currentMatrix)

In [27]:
#create our class and generate a tree assigning the solution node to finalnode
ai = uniformcostsearch(endstate,endMatrix,StartingMatrix,options)
print(StartingMatrix)
finalnode = ai.generatetree()

[[5. 3. 2.]
 [4. 6. 1.]
 [7. 8. 0.]]
iteration
chosen node
[[5. 3. 2.]
 [4. 6. 1.]
 [7. 8. 0.]]
7
iteration
chosen node
[[5. 3. 2.]
 [4. 6. 0.]
 [7. 8. 1.]]
7
iteration
chosen node
[[5. 3. 2.]
 [4. 6. 1.]
 [7. 0. 8.]]
7
iteration
chosen node
[[5. 3. 2.]
 [4. 0. 1.]
 [7. 6. 8.]]
6
iteration
chosen node
[[5. 0. 2.]
 [4. 3. 1.]
 [7. 6. 8.]]
6
iteration
chosen node
[[5. 2. 0.]
 [4. 3. 1.]
 [7. 6. 8.]]
5
iteration
chosen node
[[5. 2. 1.]
 [4. 3. 0.]
 [7. 6. 8.]]
5
iteration
chosen node
[[5. 2. 1.]
 [4. 3. 8.]
 [7. 6. 0.]]
5
iteration
chosen node
[[5. 2. 1.]
 [4. 0. 3.]
 [7. 6. 8.]]
5
iteration
chosen node
[[5. 2. 1.]
 [0. 4. 3.]
 [7. 6. 8.]]
5
iteration
chosen node
[[0. 2. 1.]
 [5. 4. 3.]
 [7. 6. 8.]]
5
iteration
chosen node
[[5. 3. 2.]
 [0. 4. 1.]
 [7. 6. 8.]]
6
iteration
chosen node
[[5. 3. 2.]
 [4. 1. 0.]
 [7. 6. 8.]]
6
iteration
chosen node
[[0. 5. 2.]
 [4. 3. 1.]
 [7. 6. 8.]]
6
iteration
chosen node
[[5. 2. 1.]
 [4. 3. 8.]
 [7. 0. 6.]]
6
iteration
chosen node
[[5. 0. 1.]
 [4. 2. 3.]
 [

In [28]:
#go through each parent node and print out its tree creating a trace of moved used to create the final matrix
node2 = finalnode
i = 0
count = 0
print(node2.depth)
print('starts at the end state and back to tracks to intail matrix due to storage method')
while i < 2:
    count += 1
    if(node2.pastnode == None):
        print('the start')
        i = 3
        print('it required this many steps to reach the final state')
        print(count)
    print(node2.currentMatrix)
    node2 = node2.pastnode

40
starts at the end state and back to tracks to intail matrix due to storage method
[[1. 2. 3.]
 [8. 0. 4.]
 [7. 6. 5.]]
[[1. 2. 3.]
 [0. 8. 4.]
 [7. 6. 5.]]
[[1. 2. 3.]
 [7. 8. 4.]
 [0. 6. 5.]]
[[1. 2. 3.]
 [7. 8. 4.]
 [6. 0. 5.]]
[[1. 2. 3.]
 [7. 8. 4.]
 [6. 5. 0.]]
[[1. 2. 3.]
 [7. 8. 0.]
 [6. 5. 4.]]
[[1. 2. 3.]
 [7. 0. 8.]
 [6. 5. 4.]]
[[1. 2. 3.]
 [7. 5. 8.]
 [6. 0. 4.]]
[[1. 2. 3.]
 [7. 5. 8.]
 [0. 6. 4.]]
[[1. 2. 3.]
 [0. 5. 8.]
 [7. 6. 4.]]
[[1. 2. 3.]
 [5. 0. 8.]
 [7. 6. 4.]]
[[1. 2. 3.]
 [5. 8. 0.]
 [7. 6. 4.]]
[[1. 2. 0.]
 [5. 8. 3.]
 [7. 6. 4.]]
[[1. 0. 2.]
 [5. 8. 3.]
 [7. 6. 4.]]
[[1. 8. 2.]
 [5. 0. 3.]
 [7. 6. 4.]]
[[1. 8. 2.]
 [5. 3. 0.]
 [7. 6. 4.]]
[[1. 8. 2.]
 [5. 3. 4.]
 [7. 6. 0.]]
[[1. 8. 2.]
 [5. 3. 4.]
 [7. 0. 6.]]
[[1. 8. 2.]
 [5. 0. 4.]
 [7. 3. 6.]]
[[1. 0. 2.]
 [5. 8. 4.]
 [7. 3. 6.]]
[[1. 2. 0.]
 [5. 8. 4.]
 [7. 3. 6.]]
[[1. 2. 4.]
 [5. 8. 0.]
 [7. 3. 6.]]
[[1. 2. 4.]
 [5. 0. 8.]
 [7. 3. 6.]]
[[1. 2. 4.]
 [5. 3. 8.]
 [7. 0. 6.]]
[[1. 2. 4.]
 [5. 3. 8.]
 [7