# Slider Puzzle A-star Algorithm

In [1]:
import random
import pandas as pd
import numpy as np
import math
#create our matrix starting state, 0 will denote the open space
options = [0,1,2,3,4,5,6,7,8]
#randomly select the order of starting state
random.shuffle(options)
print(options)
StartingMatrix = np.zeros((3,3))
#populate the matrix
for i in range (0, 3):
    print(i)
    for j in range (0, 3):
        print(j)
        StartingMatrix[i][j] = options[(i*3)+j]
print(StartingMatrix)
# create our end state matrix
endMatrix = np.zeros((3,3))
endstate = [1,2,3,8,0,4,7,6,5]
for i in range (0, 3):
    print(i)
    for j in range (0, 3):
        print(j)
        endMatrix[i][j] = endstate[(i*3)+j]
print(endMatrix)

[6, 4, 7, 0, 5, 3, 2, 1, 8]
0
0
1
2
1
0
1
2
2
0
1
2
[[6. 4. 7.]
 [0. 5. 3.]
 [2. 1. 8.]]
0
0
1
2
1
0
1
2
2
0
1
2
[[1. 2. 3.]
 [8. 0. 4.]
 [7. 6. 5.]]


In [2]:
#we will define cost as the number of pieces out of place
import math as math
class Astar:
    #defines the dataset are
    def __init__(self, endstate, endMatrix, startingMaxtrix, startingStatelist):
        self.endstate = endstate
        self.endMatrix = endMatrix
        self.startingMaxtrix = startingMaxtrix
        self.startingStatelist = startingStatelist
        #holds the map its self
    def costOfCandidateState(self, startingMaxtrix, endMatrix, depth):
        cost = 0
        cost2 = 0
        for i in range (0, 3):    
            for j in range (0, 3):
                if(startingMaxtrix[i][j] != 0):
                    valinstart = startingMaxtrix[i][j]
                    for n in range (0, 3):         
                        for m in range (0, 3):
                            if(endMatrix[n][m] == valinstart):
                                cost += abs(i-n) + abs(j - m)
        cost += depth                    
        for i in range (0, 3): 
            for j in range (0, 3):
                if(startingMaxtrix[i][j] != endMatrix[i][j] and startingMaxtrix[i][j] != 0):
                    cost2 += 1
        if(cost2 == 0):
            cost = 0
        return(cost)
        
    def findPossibleMoves(self, currentMatrixState, depth ,node):
        possibleMoves = []
        tempMatrix = np.zeros((3,3))
        depth += 1
        for i in range (0, 3):
            for j in range (0, 3):
                tempMatrix[i][j] = currentMatrixState[i][j]
        zerolocx = 0
        zerolocy = 0
        cost = -1
        for i in range (0, 3):
            for j in range (0, 3):
                if(currentMatrixState[i][j] == 0):
                    zerolocx = i
                    zerolocy = j
        
        
        if(zerolocx > 0):
            tempMatrix[zerolocx][zerolocy] = currentMatrixState[zerolocx-1][zerolocy]
            tempMatrix[zerolocx-1][zerolocy] = 0
            cost = self.costOfCandidateState(tempMatrix.copy(), self.endMatrix, node.depth)
            node4 = Node(tempMatrix.copy(), depth, cost)
            possibleMoves.append(node4)
            #possibleMoves.append(Node(tempMatrix.copy(), depth, cost))
            for i in range (0, 3):
                for j in range (0, 3):
                    tempMatrix[i][j] = currentMatrixState[i][j]
        if(zerolocx < 2):
            tempMatrix[zerolocx][zerolocy] = currentMatrixState[zerolocx+1][zerolocy]
            tempMatrix[zerolocx+1][zerolocy] = 0
            cost = self.costOfCandidateState(tempMatrix.copy(), self.endMatrix, node.depth)
            node1 = Node(tempMatrix.copy(), depth, cost)
            possibleMoves.append(node1)
            for i in range (0, 3):
                for j in range (0, 3):
                    tempMatrix[i][j] = currentMatrixState[i][j]
        if(zerolocy > 0):
            tempMatrix[zerolocx][zerolocy] = currentMatrixState[zerolocx][zerolocy-1]
            tempMatrix[zerolocx][zerolocy-1] = 0
            cost = self.costOfCandidateState(tempMatrix.copy(), self.endMatrix, node.depth)
            node2 = Node(tempMatrix.copy(), depth, cost)
            possibleMoves.append(node2)
            
            #possibleMoves.append(Node(tempMatrix.copy(), depth, cost))
            for i in range (0, 3):
                for j in range (0, 3):
                    tempMatrix[i][j] = currentMatrixState[i][j]
        if(zerolocy < 2):
            tempMatrix[zerolocx][zerolocy] = currentMatrixState[zerolocx][zerolocy+1]
            tempMatrix[zerolocx][zerolocy+1] = 0
            cost = self.costOfCandidateState(tempMatrix.copy(), self.endMatrix, node.depth)
            node3 = Node(tempMatrix.copy(), depth, cost)
            possibleMoves.append(node3)
            #possibleMoves.append(Node(tempMatrix.copy(), depth, cost))
            for i in range (0, 3):
                for j in range (0, 3):
                    tempMatrix[i][j] = currentMatrixState[i][j]
        for i in range (0, len(possibleMoves)):                      
            possibleMoves[i].pastnode = node
        return(possibleMoves)
    def generatetree(self):
        candidateNodeList = []
        candidateNodeList1 = []
        node = Node(current = self.startingMaxtrix, depth = 0, cost = -1)
        candidateNodeList.append(node)
        candidateNodeList[0].cost = self.costOfCandidateState(candidateNodeList[0].currentMatrix, self.endMatrix, candidateNodeList[0].depth)
        #candidateNodeList[0].cost = self.costOfCandidateState(condidateNodeList[0].currentMatrix, self.endMatrix)\
        matchList = []
        for i in range (0, 10000):
            #find lowest cost node
            mincost = 1000000000
            indexOfNextChoice = 0
            print('iteration')
            
            for j in range (0, len(candidateNodeList)):
                #print(candidateNodeList[j].cost)
                if(candidateNodeList[j].cost < mincost and candidateNodeList[j].cost != -1):
                    indexOfNextChoice = j
                    mincost = candidateNodeList[j].cost
                    
                    if(mincost == 0):
                        print('here')
                        print(candidateNodeList[j].currentMatrix)
                        print("total matrix's visited to reach goal state")
                        print(i)
                        return(candidateNodeList[j])
                        
            
            print('chosen node')
            print(candidateNodeList[indexOfNextChoice].currentMatrix)
            print(candidateNodeList[indexOfNextChoice].cost)
            matchList.append(candidateNodeList[indexOfNextChoice].currentMatrix) 
            candidateNodeList1 = (self.findPossibleMoves(candidateNodeList[indexOfNextChoice].currentMatrix,candidateNodeList[indexOfNextChoice].depth, candidateNodeList[indexOfNextChoice]))   
            #for m in range (0, len(candidateNodeList1)):        
            candidateNodeList = np.concatenate((candidateNodeList, candidateNodeList1), axis=0)
            
            candidateNodeList = np.delete(candidateNodeList, indexOfNextChoice, 0)
            m = 0
            while m < len(candidateNodeList):
                m2 = candidateNodeList[m].currentMatrix
                #print('m2')
                #print(m2)
                for k in range(0, len(matchList)):            
                    cost1 = 0
                    m1 = matchList[k]
                    #print('m1')
                    #print(m1)      
                    for b in range (0, 3):
                        for v in range (0, 3):                         
                            if(m1[b][v] != m2[b][v]):
                                cost1 += 1                              
                    if(cost1 == 0 and m != len(candidateNodeList)):
                        #print('check of if last node exist')
                        #print(m)
                        #print(len(candidateNodeList))
                        #print(candidateNodeList[m].currentMatrix)
                        #print(m1)
                        candidateNodeList = np.delete(candidateNodeList, m)                     
                        k = len(matchList)
                m += 1
            #for m in range (0, len(candidateNodeList)):        
                #print(candidateNodeList[i].currentMatrix)
                #print(candidateNodeList[m].currentMatrix)
                #print(candidateNodeList[m].cost) 
                
            
    

In [3]:
class Node:
    def __init__(self, current, depth, cost):
        self.currentMatrix = current
        self.depth = depth
        self.cost = cost
        self.pastnode = None
    def getdepth():
        return(depth)
    def getCurrentState():
        return(self.currentMatrix)

In [ ]:
ai = Astar(endstate,endMatrix,StartingMatrix,options)
print(StartingMatrix)
finalnode = ai.generatetree()

[[6. 4. 7.]
 [0. 5. 3.]
 [2. 1. 8.]]
iteration
chosen node
[[6. 4. 7.]
 [0. 5. 3.]
 [2. 1. 8.]]
21
iteration
chosen node
[[0. 4. 7.]
 [6. 5. 3.]
 [2. 1. 8.]]
20
iteration
chosen node
[[6. 4. 7.]
 [2. 5. 3.]
 [0. 1. 8.]]
20
iteration
chosen node
[[6. 4. 7.]
 [2. 5. 3.]
 [1. 0. 8.]]
20
iteration
chosen node
[[6. 4. 7.]
 [2. 0. 3.]
 [1. 5. 8.]]
20
iteration
chosen node
[[6. 4. 7.]
 [2. 5. 3.]
 [1. 8. 0.]]
20
iteration
chosen node
[[6. 0. 7.]
 [2. 4. 3.]
 [1. 5. 8.]]
20
iteration
chosen node
[[6. 4. 7.]
 [0. 2. 3.]
 [1. 5. 8.]]
20
iteration
chosen node
[[0. 6. 7.]
 [2. 4. 3.]
 [1. 5. 8.]]
20
iteration
chosen node
[[6. 7. 0.]
 [2. 4. 3.]
 [1. 5. 8.]]
20
iteration
chosen node
[[0. 4. 7.]
 [6. 2. 3.]
 [1. 5. 8.]]
20
iteration
chosen node
[[6. 4. 7.]
 [1. 2. 3.]
 [0. 5. 8.]]
20
iteration
chosen node
[[2. 6. 7.]
 [0. 4. 3.]
 [1. 5. 8.]]
20
iteration
chosen node
[[6. 7. 3.]
 [2. 4. 0.]
 [1. 5. 8.]]
20
iteration
chosen node
[[2. 6. 7.]
 [1. 4. 3.]
 [0. 5. 8.]]
20
iteration
chosen node
[[6. 7. 3.]

In [ ]:
node2 = finalnode
i = 0
count = 0
print(node2.depth)
print('starts at the end state and back to tracks to intail matrix due to storage method')
while i < 2:
    count += 1
    if(node2.pastnode == None):
        print('the start')
        i = 3
        print('it required this many steps to reach the final state')
        print(count)
    print(node2.currentMatrix)
    node2 = node2.pastnode